version: '3.8'
services:

  db:
    container_name: tokensmith_postgres
    image: postgres:11.5
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ""
        POSTGRES_DB: auth

  zookeeper:
    container_name: tokensmith_zookeeper
    image: tokensmith/zookeeper
    ports:
      - 2181:2181

  kafka-broker:
    container_name: tokensmith_kafka_broker
    image: tokensmith/kafka-broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
