version: '3.8'
services:

  server:
    container_name: tokensmith_server
    image: tokensmith/server
    restart: always
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -H \"Content-Type: application/json; charset=utf-8\" localhost:8080/api/public/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      AUTH_DB_URL: "jdbc:postgresql://db:5432/auth"
      AUTH_DB_USER: "postgres"
      AUTH_DB_PASSWORD: ""
      ISSUER: "https://sso.tokensmith.net"
      ALLOW_LOCAL_URLS: "true"
      ALLOW_HTTP_URLS: "true"
      MESSAGE_QUEUE_HOST: "kafka-broker:29092"

  db_migration:
    container_name: tokensmith_migrator
    image: tokensmith/db_migrator
    environment:
      AUTH_DB_HOST: "db"
      AUTH_DB_NAME: "auth"
      AUTH_DB_USER: "postgres"
      DB_MAX_ATTEMPTS: 10
