version: '3.8'
services:

  db:
    container_name: tokensmith_postgres
    image: postgres:11.5
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ""
        POSTGRES_DB: auth

  zookeeper:
    container_name: tokensmith_zookeeper
    image: tokensmith/zookeeper:v1.2
    ports:
      - 2181:2181

  kafka-broker:
    container_name: tokensmith_kafka_broker
    image: tokensmith/kafka-broker:v1.2
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092

  message-user:
    container_name: tokensmith_message_user
    image: tokensmith/message-user:v0.1
    depends_on:
      - kafka-broker
    environment:
        SMTP_HOST: ${SMTP_HOST}
        SMTP_USER: ${SMTP_USER}
        SMTP_PASSWORD: ${SMTP_PASSWORD}
        SMTP_FROM: ${SMTP_FROM}
        MESSAGE_QUEUE_HOST: kafka-broker:29092
        TOPICS: 'message-user'
