version: '3.8'
services:

  db:
    container_name: tokensmith_postgres
    image: postgres:11.5
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ""
        POSTGRES_DB: auth

  zookeeper:
    container_name: tokensmith_zookeeper
    image: tokensmith/zookeeper:v1.2.1
    ports:
      - 2181:2181
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc -w 2 localhost 2181"]
      interval: 5s
      timeout: 10s
      retries: 3

  kafka-broker:
    container_name: tokensmith_kafka_broker
    image: tokensmith/kafka-broker:v1.2.1
    restart: on-failure
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    healthcheck:
      test: ["CMD-SHELL", "echo dump | nc -w 2 zookeeper 2181 | grep broker"]
      interval: 15s
      timeout: 20s
      retries: 5

  message-user:
    container_name: tokensmith_message_user
    image: tokensmith/message-user:v0.1
    depends_on:
      - kafka-broker
    environment:
        SMTP_HOST: ${SMTP_HOST}
        SMTP_USER: ${SMTP_USER}
        SMTP_PASSWORD: ${SMTP_PASSWORD}
        SMTP_FROM: ${SMTP_FROM}
        MESSAGE_QUEUE_HOST: kafka-broker:29092
        TOPICS: 'message-user'
