version: '3.8'
services:

  db:
    container_name: tokensmith_postgres
    image: postgres:11.5
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ""
        POSTGRES_DB: auth

  kafka:
    container_name: tokensmith_kafka
    image: ts/kafka
    build:
      context: docker/kafka
      dockerfile: Dockerfile

  zookeeper:
    container_name: tokensmith_zookeeper
    image: ts/zookeeper
    build:
      context: docker/zookeeper
      dockerfile: Dockerfile
    ports:
      - 2181:2181

  kafka-broker:
    container_name: tokensmith_kafka_broker
    image: ts/kafka-broker
    depends_on:
      - zookeeper
    build:
      context: docker/kafka-broker
      dockerfile: Dockerfile
    ports:
      - 9092:9092
      - 29092:29092
